### ISSUE TITLE
Can't open osm file with JOSM

### ISSUE THREAD

**Issue by 50thomatoes50** [PropaneDragon/Cimtographer#5]
JOSM don't like to read something with id=0
It was not a node but a way in my case put I think any object will not work

**Comment by tony56a** [comment]
Hi,

As per #2, I think the issue should be fixed by changing the id offset to start from 1, which should be part of the next release.

**Comment by 50thomatoes50** [comment]
Hi
Found where it is. Just for learning purpose.
Mapper/OSM/OSMExportNew.cs
Line 103
for(int segmentId = 0; segmentId<netSegments.Length; segmentId++)
------------------------^^^

Can you make the commit? Because you already made some Pull requests

**Comment by PropaneDragon** [comment]
I'm in the process of merging everything together, and I'll get a release up as soon as possible.

**Comment by PropaneDragon** [comment]
This should be fixed now, as I've merged changes by @tony56a
